### ISSUE TITLE
[enhancement] extract text attributes keys into variables for the syntax highlighter

### ISSUE THREAD

**Issue by javatlacati** [Phosphorus15/intellij-prolog#113]
in example:

https://github.com/Phosphorus15/intellij-prolog/blob/4db827b24b91fee398eea01fd47d7fcc6c7b7c9e/src/main/scala/tech/phosphorus/intellij/prolog/syntax-defs.scala#L23

if you have it extracted

```
public static final TextAttributesKey COMMENT =
            createTextAttributesKey("COMMENT", DefaultLanguageHighlighterColors.LINE_COMMENT);
```

you can easily configure colors setting page

```
public class PrologColorSettingsPage implements ColorSettingsPage {

    private static final AttributesDescriptor[] DESCRIPTORS = new AttributesDescriptor[]{
            new AttributesDescriptor("Line Comment", PrologSyntaxHighlighter.COMMENT),
    };

    @Override
    public AttributesDescriptor @NotNull [] getAttributeDescriptors() {
        return DESCRIPTORS;
    }
```

**Comment by Phosphorus15** [comment]
That sounds like a great idea! Are you interested in turning this into a PR? My hands are tight this week, so I might be unable to make this improvement happen soon.

**Comment by javatlacati** [comment]
Sorry I still haven't learnt Scala and wouldn't know how to do the changes



El 8 ene 2023, a la(s) 4:17, phosphorus ***@***.***> escribió:

﻿

That sounds like a great idea! Are you interested in turning this into a PR? My hands are tight this week, so I might be unable to make this improvement happen soon.

**Comment by Phosphorus15** [comment]
The new plugin was submitted to JetBrains' marketplace for moderation; this issue is marked resolved :P, thanks for the good work @javatlacati
