### ISSUE TITLE
operator not recognized =..

### ISSUE THREAD

**Issue by javatlacati** [Phosphorus15/intellij-prolog#130]
The operator `=..`  is not defined, and probably some others.

Such operator [is documented here](https://www.swi-prolog.org/pldoc/man?section=operators).

## How to reproduce

Example code:

```
dbretrieve2(TupleDesc, QueueNum, TupCall ) :-
      TupleDesc =.. [_:TupleList] ,%TupleHead
      repeat,
      p_getTuple(TupleList,Eof, TupCall) ,
      ( (Eof == true, p_freeQueue(QueueNum) ,! ,fail) ;
      true) .
```

which produces the error:

`':-' or const_id expected, got '.'`

## proposed solution

I think the operator can be added in the file prologLexer.flex

**Comment by Phosphorus15** [comment]
Done! thanks for the good work.
