### ISSUE TITLE
Address conflicts with logtalk plugin

### ISSUE THREAD

**Issue by Phosphorus15** [Phosphorus15/intellij-prolog#15]
refer to #13 and #14

**Comment by ice1000** [comment]
I suggest renaming the language internal ID into SwiProlog

**Comment by Phosphorus15** [comment]
I'd prefer `PrologIJ` caz supports for ecl-prolog and datalog are now planned for this plugin.

**Comment by Phosphorus15** [comment]
I do expect #13 and #14 to popup again before 77a3e5a comes to release
