### ISSUE TITLE
Parsing error leading to inaccurate error tooltip

### ISSUE THREAD

**Issue by emacstheviking** [Phosphorus15/intellij-prolog#20]
Hi, I just installed your plugin into a fresh install of Idea on Mint, and when I opened one of my files that compiles and runs just fine, I was presented with the message:

')' expected, got ','

I've attached a screenshot. Under PceEmacs there is no error.
![parseerror](https://user-images.githubusercontent.com/816837/80582536-cce1ac00-8a06-11ea-822d-5207bd27f70f.png)

**Comment by emacstheviking** [comment]
Fantastic response! If only every product was this responsive. Is it just a matter of reinstalling / updating the plugin from inside IntelliJ now ?

**Comment by Phosphorus15** [comment]
> Fantastic response! If only every product was this responsive. Is it just a matter of reinstalling / updating the plugin from inside IntelliJ now ?

No, jetbrains central repo. is always slow upon plugin moderation, I've uploaded a GitHub release instead so you can download & install it :
https://github.com/Phosphorus15/intellij-prolog/releases/tag/v0.1.2-hotfix

Thank you so much for your timely feekback !

**Comment by emacstheviking** [comment]
@Phosphorus15  no worries, I am building my own locally but I will stop it as it is taking a while!! Thanks again for being so quick....Prolog is keeping me sane during lock-down! :)

**Comment by emacstheviking** [comment]
Installed and 100% perfect. My build failed in the end anyway, something about a missing intellij dependency. I might try again later as I would be interested in add some features over time, like not hardcoding the "-t halt" into the run command for example. Top of my list would be to "signal" a REPL session that "make/0" should run etc. That would be a great first feature...or have I missed something??

**Comment by Phosphorus15** [comment]
Almost sure its problem with maven mirrors in `build.gradle`, will figure a way out later. For now you can set your system environment `CI` to `true` to address this (e.g. `export CI=true`).

**Comment by Phosphorus15** [comment]
It'd be highly appreciated if you can create an issue or even pr to share your great ideas of improving this plugin. (the `make/0` one sounds promising)

Btw, you made a good point there (about the Prolog keeps sanity stuff :D) and I do hope you'll be alright during the lock down.

**Comment by emacstheviking** [comment]
@Phosphorus15 I'd be more than happy to make issue-requests or even to have a go. I have not used Scala for a few years (I wrote an Android app with it and sbt many moons ago but never released it). I can see that the build probably had was due to an authentication token that maybe you have hidden from view and rightly so

    > Could not get unknown property 'intellijPublishToken' for task ':publishPlugin' of type
    > org.jetbrains.intellij.tasks.PublishTask.

If I managed to get a working build environment on my local machine I would be more than happy to contribute. Idea is a fantastic IDE, I use it almost as much as Emacs these days because it provides so much extra support.

So...any tips on getting it to build?

**Comment by Phosphorus15** [comment]
sorry for a bit delay, one way to solve this is to create an dummy "gradle.properties" file and feed it with a single line of "intellijPublishToken=dummyToken".
Since gradle.properties is set to be ignored, you should not worry about undesired changes on this repo
