### ISSUE TITLE
Bug: Simple commenting on/off of current line or region with wrong characater

### ISSUE THREAD

**Issue by emacstheviking** [Phosphorus15/intellij-prolog#23]
Currently when I select a region or use the current line, pressing "Ctrl-/" to apply the comment style seems to be using the # (pound/hash) character not the expected % (percent) character.
Forgive me if this is not a bug but it doesn't feel right!

**Comment by Phosphorus15** [comment]
That's strange, it seems to use % correctly on my testing IDE. Could you post a screenshot as reference?

**Comment by emacstheviking** [comment]
Hi @Phosphorus15 ...I've (tried to) attached a short video grab so you can see it in action. Bear in mind I am using the hotfix version installed locally...maybe that's significant ?
![commentregion](https://user-images.githubusercontent.com/816837/80637461-f5919200-8a56-11ea-88dc-2579041e7028.png)

**Comment by Phosphorus15** [comment]
strangely I could not reproduce such problem, maybe I should try install the hot fix myself..

**Comment by emacstheviking** [comment]
Might be a good idea. I didn't try that particular key sequence with the
plugin from JB servers from within the IDE so I can't compare.

**Comment by emacstheviking** [comment]
Ah, I didn't realise @Phosphorus15/intellij-prolog
<reply@reply.github.com>
that... OK I will try that. I have a small confession to make as well about
one of the other tickets...I will update that ticket now! (facepalm)

**Comment by Phosphorus15** [comment]
closed with #25
