### ISSUE TITLE
Bug: single quote in comment breaks syntax coloring

### ISSUE THREAD

**Issue by emacstheviking** [Phosphorus15/intellij-prolog#25]
Screenshot attached. Line 26 of the left of the image has a single quote in the word "don't" which breaks the syntax coloring. On the right you can see that removing the quote makes it well again.
![commentquotebug](https://user-images.githubusercontent.com/816837/80657092-ab220c80-8a7a-11ea-91a0-616d05a84c64.png)

**Comment by Phosphorus15** [comment]
wonder if there's any other `'` prior to the `don't` one, guess this is where the problem arise

**Comment by emacstheviking** [comment]
This is NOT a bug I think because I have realised that between uninstalling the original JB download and then installing the hot fix, the file association for *.pl had reverted to Perl. This means that I had not noticed that syntax colouring had reduced in quality as I had not really had the chance to see it anyway.

My sincerest apologies! I typed the same comment and it appears just fine.

**Comment by Phosphorus15** [comment]
Seems like we'll keep quarreling with our `Perl` friends :P
