### ISSUE TITLE
Incompatible with (at least) IntelliJ 2021.1.1

### ISSUE THREAD

**Issue by UweKrause** [Phosphorus15/intellij-prolog#73]
It is not possible to install this plugin for recent intellij versions.

> IntelliJ IDEA Ultimate — 2020.3.3 — 2020.3.4

https://plugins.jetbrains.com/plugin/13954-prolog/versions/stable/116226

**Comment by UweKrause** [comment]
I tried to manually install your latest release (github release), but thats not possible too:
`Plugin 'Prolog' (version '0.1.2.2-lts') is not compatible with the current version of the IDE, because it requires build 203.* or older but the current build is PY-211.7142.13`
(for pyCharm 2021.1.1)

**Comment by Phosphorus15** [comment]
Although I'd suggest you to upgrade your IntelliJ IDEA. It's true that the plugin should support IDEA older than 2021.3. I'll see if there's a way to address this problem in next release.
For now you can try install older releases of this plugin as a makeshift solution.

**Comment by Phosphorus15** [comment]
Since 6bd2399 the plugin supports IntelliJ IDEA 2022.2.2, for which I shall consider this issue could be closed
