### ISSUE TITLE
IntelliJ 2021 Support

### ISSUE THREAD

**Issue by NickGeek** [Phosphorus15/intellij-prolog#80]
Hi,
The current plugin is marked as not supporting IntelliJ 2021. It would be awesome if there was an update to get it running.

Thanks!

**Comment by fan-tom** [comment]
duplicate of #73

**Comment by Phosphorus15** [comment]
Since 6bd2399 the plugin supports IntelliJ IDEA 2022.2.2, for which I shall consider this issue could be closed
